# Generated by Django 5.1 on 2024-08-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='odometer_last',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(default='AWAITING_PAYMENT', max_length=20),
        ),
    ]
