# Generated by Django 5.1 on 2024-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_odometer_last_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
