# Generated by Django 5.1 on 2024-08-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rental_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
